In [23]:
#Створіть одновимірний масив (вектор) зі значеннями квадратних коренів з кожного натурального числа, починаючи з 1, та виведіть його значення.
import math

# Встановіть кількість натуральних чисел, для яких потрібно знайти квадратний корінь
n = 10  # Наприклад, для перших 10 чисел

# Створюємо список з квадратних коренів
square_roots = [math.sqrt(i) for i in range(1, n + 1)]

# Виводимо значення
print("Масив квадратних коренів:")
print(square_roots)

Масив квадратних коренів:
[1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979, 2.449489742783178, 2.6457513110645907, 2.8284271247461903, 3.0, 3.1622776601683795]


In [38]:
#Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями коренів 4 ступеня перших дійсних чисел
import numpy as np

# Розмір матриці
rows, cols = 3, 3

# Кількість елементів у матриці
num_elements = rows * cols

# Створюємо матрицю розміром 3x3, заповнену коренями четвертого ступеня
matrix = np.zeros((rows, cols))

# Заповнюємо матрицю значеннями коренів четвертого ступеня
for i in range(rows):
    for j in range(cols):
        number = i * cols + j + 1  # Дійсні числа починаються з 1
        matrix[i, j] = number ** (1/4)

# Виводимо матрицю
print("Матриця коренів четвертого ступеня:")
print(matrix)


Матриця коренів четвертого ступеня:
[[1.         1.18920712 1.31607401]
 [1.41421356 1.49534878 1.56508458]
 [1.62657656 1.68179283 1.73205081]]


In [25]:
#Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від 1 до 50 та знайдіть суму елементів кожного рядка.
import numpy as np

# Розмір матриці
rows, cols = 3, 3

# Створюємо матрицю розміром 3x3, заповнену випадковими числами від 1 до 50
matrix = np.random.randint(1, 51, size=(rows, cols))

# Виводимо матрицю
print("Матриця:")
print(matrix)

# Знаходимо суму елементів кожного рядка
row_sums = np.sum(matrix, axis=1)

# Виводимо суму елементів кожного рядка
print("\nСуми елементів кожного рядка:")
for i, row_sum in enumerate(row_sums):
    print(f"Рядок {i + 1}: {row_sum}")


Матриця:
[[34  7 29]
 [25 17  1]
 [ 5 41 30]]

Суми елементів кожного рядка:
Рядок 1: 70
Рядок 2: 43
Рядок 3: 76


In [26]:
#Створіть масив розміром 4x4, заповніть його випадковими дійсними числами від -0.9 до 0.9 та виведіть його значення.
import numpy as np

# Розмір матриці
rows, cols = 4, 4

# Генеруємо матрицю розміром 4x4 з випадковими дійсними числами від -0.9 до 0.9
matrix = np.random.uniform(-0.9, 0.9, size=(rows, cols))

# Виводимо матрицю
print("Матриця з випадковими дійсними числами:")
print(matrix)


Матриця з випадковими дійсними числами:
[[-0.18203986  0.47489568 -0.17012862 -0.74557273]
 [ 0.02409195 -0.10199118  0.67714904  0.31643626]
 [-0.65326418  0.89584023  0.48533195  0.67497198]
 [-0.57868532 -0.70908704 -0.63001702 -0.57755384]]


In [27]:
#Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та виконайте на них поелементні операції додавання, віднімання та множення.
import numpy as np

# Розмір масивів
size = 7

# Генеруємо два одновимірних масиви з випадковими цілими числами від 1 до 5
array1 = np.random.randint(1, 6, size=size)
array2 = np.random.randint(1, 6, size=size)

# Виводимо масиви
print("Масив 1:")
print(array1)
print("Масив 2:")
print(array2)

# Виконуємо поелементні операції
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

# Виводимо результати операцій
print("\nРезультат додавання:")
print(addition)
print("Результат віднімання:")
print(subtraction)
print("Результат множення:")
print(multiplication)


Масив 1:
[5 5 4 3 1 4 5]
Масив 2:
[2 1 3 3 1 1 2]

Результат додавання:
[7 6 7 6 2 5 7]
Результат віднімання:
[3 4 1 0 0 3 3]
Результат множення:
[10  5 12  9  1  4 10]


In [28]:
#Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 0 до 5 та знайдіть їх добуток.
import numpy as np

# Розмір матриць
rows, cols = 3, 3

# Генеруємо дві матриці розміром 3x3 з випадковими цілими числами від 0 до 5
matrix1 = np.random.randint(0, 6, size=(rows, cols))
matrix2 = np.random.randint(0, 6, size=(rows, cols))

# Виводимо матриці
print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)

# Знаходимо добуток матриць
product = np.dot(matrix1, matrix2)

# Виводимо результат
print("\nДобуток матриць:")
print(product)


Матриця 1:
[[3 3 1]
 [1 1 3]
 [4 1 0]]

Матриця 2:
[[3 1 1]
 [1 2 5]
 [4 5 3]]

Добуток матриць:
[[16 14 21]
 [16 18 15]
 [13  6  9]]


In [29]:
#Створіть дві матриці розміром 2x3 та 3x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 7 та перемножте їх між собою.
import numpy as np

# Розміри матриць
rows1, cols1 = 2, 3  # Розмір першої матриці
rows2, cols2 = 3, 4  # Розмір другої матриці

# Генеруємо дві матриці з випадковими цілими числами від 1 до 7
matrix1 = np.random.randint(1, 8, size=(rows1, cols1))
matrix2 = np.random.randint(1, 8, size=(rows2, cols2))

# Виводимо матриці
print("Матриця 1 (розмір 2x3):")
print(matrix1)
print("\nМатриця 2 (розмір 3x4):")
print(matrix2)

# Перемножуємо матриці
product = np.dot(matrix1, matrix2)

# Виводимо результат
print("\nДобуток матриць:")
print(product)


Матриця 1 (розмір 2x3):
[[2 1 5]
 [5 5 6]]

Матриця 2 (розмір 3x4):
[[2 7 1 3]
 [2 4 4 3]
 [6 1 6 4]]

Добуток матриць:
[[36 23 36 29]
 [56 61 61 54]]


In [30]:
#Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 15 та знайдіть її обернену матрицю.
import numpy as np

# Розмір матриці
size = 2

# Генеруємо матрицю розміром 2x2 з випадковими цілими числами від 1 до 15
matrix = np.random.randint(1, 16, size=(size, size))

# Виводимо матрицю
print("Матриця:")
print(matrix)

# Перевіряємо, чи матриця є оберненою (перевіряючи детермінант)
det = np.linalg.det(matrix)
if det == 0:
    print("\nМатриця є виродженою (детермінант дорівнює 0). Обернена матриця не існує.")
else:
    # Знаходимо обернену матрицю
    inverse_matrix = np.linalg.inv(matrix)

    # Виводимо обернену матрицю
    print("\nОбернена матриця:")
    print(inverse_matrix)


Матриця:
[[ 2 10]
 [12  3]]

Обернена матриця:
[[-0.02631579  0.0877193 ]
 [ 0.10526316 -0.01754386]]


In [31]:
#Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 3 до 15 та транспонуйте її.
import numpy as np

# Розмір матриці
size = 3

# Генеруємо матрицю розміром 3x3 з випадковими цілими числами від 3 до 15
matrix = np.random.randint(3, 16, size=(size, size))

# Виводимо оригінальну матрицю
print("Оригінальна матриця:")
print(matrix)

# Транспонуємо матрицю
transposed_matrix = np.transpose(matrix)

# Виводимо транспоновану матрицю
print("\nТранспонована матриця:")
print(transposed_matrix)


Оригінальна матриця:
[[13  7 15]
 [12 10  9]
 [ 6 15  8]]

Транспонована матриця:
[[13 12  6]
 [ 7 10 15]
 [15  9  8]]


In [32]:
#Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.
import numpy as np

# Розміри матриці та вектора
matrix_rows, matrix_cols = 3, 4
vector_size = 4

# Генеруємо матрицю розміром 3x4 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(matrix_rows, matrix_cols))

# Генеруємо вектор розміром 4x1 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=(vector_size, 1))

# Виводимо матрицю та вектор
print("Матриця (розмір 3x4):")
print(matrix)
print("\nВектор (розмір 4x1):")
print(vector)

# Знаходимо добуток матриці на вектор
product = np.dot(matrix, vector)

# Виводимо результат
print("\nДобуток матриці на вектор:")
print(product)


Матриця (розмір 3x4):
[[4 6 4 6]
 [4 4 6 2]
 [6 7 2 4]]

Вектор (розмір 4x1):
[[ 5]
 [10]
 [ 8]
 [ 7]]

Добуток матриці на вектор:
[[154]
 [122]
 [144]]


In [33]:
#Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.
import numpy as np

# Розміри матриці та вектора
matrix_rows, matrix_cols = 2, 3
vector_size = 3

# Генеруємо матрицю розміром 2x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.uniform(0, 1, size=(matrix_rows, matrix_cols))

# Генеруємо вектор розміром 3x1 з випадковими дійсними числами від 0 до 1
vector = np.random.uniform(0, 1, size=(vector_size, 1))

# Виводимо матрицю та вектор
print("Матриця (розмір 2x3):")
print(matrix)
print("\nВектор (розмір 3x1):")
print(vector)

# Знаходимо добуток матриці на вектор
product = np.dot(matrix, vector)

# Виводимо результат
print("\nДобуток матриці на вектор:")
print(product)


Матриця (розмір 2x3):
[[0.63584223 0.49146839 0.62145873]
 [0.50859764 0.57181353 0.1110804 ]]

Вектор (розмір 3x1):
[[0.32935816]
 [0.98368018]
 [0.16777392]]

Добуток матриці на вектор:
[[0.79713211]
 [0.74862881]]


In [34]:
#Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та знайдіть добуток всіх елементів першої матриці
import numpy as np
from functools import reduce
import operator

# Розмір матриць
size = 3

# Генеруємо дві матриці розміром 3x3 з випадковими цілими числами від 1 до 5
matrix1 = np.random.randint(1, 6, size=(size, size))
matrix2 = np.random.randint(1, 6, size=(size, size))

# Виводимо обидві матриці
print("Матриця 1 (розмір 3x3):")
print(matrix1)
print("\nМатриця 2 (розмір 3x3):")
print(matrix2)

# Знаходимо добуток всіх елементів першої матриці
product_of_elements = reduce(operator.mul, matrix1.flatten(), 1)

# Виводимо результат
print("\nДобуток всіх елементів першої матриці:")
print(product_of_elements)


Матриця 1 (розмір 3x3):
[[5 4 4]
 [1 3 2]
 [4 3 2]]

Матриця 2 (розмір 3x3):
[[1 4 5]
 [3 5 3]
 [3 1 4]]

Добуток всіх елементів першої матриці:
11520


In [35]:
#Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть різницю їх елементів.
import numpy as np

# Розмір матриць
size = 3

# Генеруємо дві матриці розміром 3x3 з випадковими дійсними числами від -1 до 1
matrix1 = np.random.uniform(-1, 1, size=(size, size))
matrix2 = np.random.uniform(-1, 1, size=(size, size))

# Виводимо обидві матриці
print("Матриця 1 (розмір 3x3):")
print(matrix1)
print("\nМатриця 2 (розмір 3x3):")
print(matrix2)

# Знаходимо різницю між матрицями
difference = matrix1 - matrix2

# Виводимо результат
print("\nРізниця між матрицями:")
print(difference)


Матриця 1 (розмір 3x3):
[[ 0.97266391 -0.48792226 -0.88467857]
 [ 0.29941406  0.63104189  0.63718681]
 [-0.34472937 -0.81873494 -0.27059834]]

Матриця 2 (розмір 3x3):
[[ 0.7587003  -0.69343188  0.95684903]
 [ 0.61849545  0.94990284 -0.62862603]
 [-0.2747676   0.69207325 -0.84570084]]

Різниця між матрицями:
[[ 0.21396361  0.20550962 -1.84152759]
 [-0.31908138 -0.31886094  1.26581284]
 [-0.06996176 -1.5108082   0.5751025 ]]


In [36]:
#Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -3 до 3 та знайдіть суму елементів на головній діагоналі.
import numpy as np

# Розмір матриці
size = 3

# Генеруємо матрицю розміром 3x3 з випадковими дійсними числами від -3 до 3
matrix = np.random.uniform(-3, 3, size=(size, size))

# Виводимо матрицю
print("Матриця (розмір 3x3):")
print(matrix)

# Знаходимо суму елементів на головній діагоналі
diagonal_sum = np.trace(matrix)

# Виводимо результат
print("\nСума елементів на головній діагоналі:")
print(diagonal_sum)


Матриця (розмір 3x3):
[[-1.16545282  0.37596376 -2.34113208]
 [-2.41205866  2.55180221  2.51663689]
 [-2.10883406 -2.98374914  0.81437302]]

Сума елементів на головній діагоналі:
2.2007224102143472


In [37]:
#Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить суму елементів кожного стовпця матриці.
import numpy as np

# Розмір матриці
size = 3

# Генеруємо матрицю розміром 3x3 з випадковими дійсними числами від -0.5 до 0.5
matrix = np.random.uniform(-0.5, 0.5, size=(size, size))

# Виводимо матрицю
print("Матриця (розмір 3x3):")
print(matrix)

# Знаходимо суму елементів кожного стовпця
column_sums = np.sum(matrix, axis=0)

# Перетворюємо результат на вектор-стовпчик
column_sums_vector = column_sums.reshape(-1, 1)

# Виводимо вектор-стовпчик
print("\nВектор-стовпчик, що містить суму елементів кожного стовпця:")
print(column_sums_vector)


Матриця (розмір 3x3):
[[-0.33115799  0.18568002  0.02971301]
 [ 0.46896665 -0.45164391 -0.34477943]
 [ 0.21140237  0.14427624  0.01688316]]

Вектор-стовпчик, що містить суму елементів кожного стовпця:
[[ 0.34921103]
 [-0.12168765]
 [-0.29818327]]


In [40]:
#Висновок
#На цій лабораторній роботі я пригадав основні елементи лінійної алгебри, та написання програм для розв'язування цих самих лінійних задач